### ISSUE TITLE
Script async load on NextJS

### ISSUE THREAD

**Issue by jrdi** [tinybirdco/tinybird-tracker#25]
Note that I'm not a JS expert but trying to integrate the tracker in a NextJS site I had to include the following code. I was forced to explicitly wait until the script is loaded to be able to send the first event. After that, everything is handled using route change events.

```js
<script
  async
  data-token={`${process.env.NEXT_PUBLIC_TB_APPEND_TOKEN}`}
  data-source={`${process.env.NEXT_PUBLIC_TB_DATASOURCE}`}
  src="https://cdn.tinybird.co/static/js/t.js"
  id="tbscript"
/>
<script
  dangerouslySetInnerHTML={{
    __html: `
    document.getElementById("tbscript").onload = function(){
      window.tinybird('pageload', { referrer: document.referrer, page: window.location.pathname });
    }
  `,
  }}
/>
```

The GA code for integrating in NextJS is something like:

```js
<script async src="https://www.googletagmanager.com/gtag/js?id=${YOUR_TRACKING_ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', ${YOUR_TRACKING_ID});
</script>
```

Looks like they use `windows.dataLayer` to store events. If I followed the code properly, we follow a similar approach adding events to the localStorage. So in theory we can push events there while initializing but I was afraid of following that path and running into some race condition. Do you know the best approach here?

**Comment by xavijam** [comment]
We already provide https://github.com/tinybirdco/next-tinybird, let me know if that works for you :)

**Comment by assemmarwan** [comment]
@xavijam Seems like the package is not compatible with Next 13. Getting this:

```
npm ERR! Found: next@13.1.1
npm ERR! node_modules/next
npm ERR!   next@"13.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^11.0.0" from @tinybirdco/next-tinybird@0.0.3
npm ERR! node_modules/@tinybirdco/next-tinybird
npm ERR!   @tinybirdco/next-tinybird@"*" from the root project
```
